tasks:
  - name: prebuild
    init: |
      echo docker-build:
      cat ~/docker-build-date.txt
      echo prebuild:
      node -p 'Date()' >prebuild-date.txt
      cat prebuild-date.txt
      echo 'env | grep GRADLE'
      env | grep GRADLE

image:
  file: gitpod.Dockerfile